FROM node:22-bullseye-slim

WORKDIR /app

# Instala dependências nativas (caso tenha libs com build)
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

# Copia apenas manifestos para instalar dependências
COPY package.json yarn.lock ./

# Instala todas dependências incluindo devDependencies
RUN yarn install --frozen-lockfile

# Exponha a porta do Nest
EXPOSE 3000

# Comando padrão para desenvolvimento
CMD ["yarn", "start:dev"]