sonar.projectKey=webshop-api
sonar.host.url=http://localhost:9000
sonar.token=sqp_08314586a0d7555d1dcded916b38f91401c2d7ca
sonar.javascript.lcov.reportPaths=test/coverage-e2e/lcov.info
sonar.junit.reportPaths=test/coverage-e2e/test-report.xml
sonar.sources=src
sonar.tests=test
sonar.inclusions=**/*.ts
sonar.test.inclusions=test/**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,node_modules/**
sonar.qualitygate.wait=true

sonar.scm.disabled=true
# sonar.scm.provider=git
sonar.qualitygate.ignoreSmallChanges=false

sonar.cpd.minimumLines=2
sonar.cpd.minimumTokens=2
# Forçar análise de duplicações
sonar.cpd.javascript.minimumLines=2
sonar.cpd.javascript.minimumTokens=2
sonar.cpd.typescript.minimumLines=2
sonar.cpd.typescript.minimumTokens=2

# --------------------------
# Informações do projeto
# --------------------------
# sonar.projectKey=order-mngt-api
# sonar.projectName=Order Management API
# # sonar.projectVersion=1.0

# # --------------------------
# # Servidor Sonar
# # --------------------------
# sonar.host.url=http://localhost:9000
# sonar.token=sqp_dfdd1cf03329c7fd9da9ec57734187231e543b55

# # --------------------------
# # Fontes e testes
# # --------------------------
# sonar.sources=src
# sonar.tests=src
# sonar.inclusions=**
# sonar.test.inclusions=src/**/*.spec.ts

# # --------------------------
# # Cobertura e execução de testes
# # --------------------------
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-reporter.xml

# # --------------------------
# # SCM (Git) – opcional, usado para blame
# # --------------------------
# sonar.scm.provider=git

# # --------------------------
# # Detecção de duplicações (CPD) mínima
# # --------------------------
# sonar.cpd.minimumLines=2
# sonar.cpd.minimumTokens=2
# sonar.cpd.javascript.minimumLines=2
# sonar.cpd.javascript.minimumTokens=2
# sonar.cpd.typescript.minimumLines=2
# sonar.cpd.typescript.minimumTokens=2

# --------------------------
# Quality Gate
# --------------------------
# A regra de zero duplicações deve ser configurada no SonarQube Web UI:
# Duplicated Lines (%) <= 0%
# Assim qualquer duplicação fará o Quality Gate falhar